services:
  my-service:
    image: my-image
    environment:
      - JWT_SECRET=${JWT_SECRET}

      - OAUTH2_KAKAO_ID=${OAUTH2_KAKAO_ID}
      - OAUTH2_KAKAO_SECRET=${OAUTH2_KAKAO_SECRET}

      - OAUTH2_NAVER_ID=${OAUTH2_NAVER_ID}
      - OAUTH2_NAVER_SECRET=${OAUTH2_NAVER_SECRET}

      - OAUTH2_GOOGLE_ID=${OAUTH2_GOOGLE_ID}
      - OAUTH2_GOOGLE_SECRET=${OAUTH2_GOOGLE_SECRET}

      - PROD_MYSQL_HOST=${PROD_MYSQL_HOST}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

      - PROD_REDIS_HOST=${PROD_REDIS_HOST}
      - PROD_REDIS_PORT=${PROD_REDIS_PORT}

      - PROD_BASE_URL=${PROD_BASE_URL}

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
